# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='codigo',
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo_geral',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
