# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_de_nascimento',
            field=models.DateField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
