# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aluno_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
